=== timofurrer/hslu-xml-technologies/app/xsd/sporttypes.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sporttypes">
    <xs:complexType>
      <xs:sequence minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="sporttype"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="sporttype">
    <xs:complexType>
      <xs:all>
        <xs:element name="title" type="xs:string"/>
      </xs:all>
      <xs:attribute name="id" type="xs:decimal" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== timofurrer/hslu-xml-technologies/app/xml/sporttypes.xml
<?xml version="1.0" encoding="utf-8"?>

<sporttypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/sporttypes.xsd">
    <sporttype id="1">
      <title>Sommersport</title>
    </sporttype>
    <sporttype id="2">
      <title>Wintersport</title>
    </sporttype>
    <sporttype id="3">
      <title>Laufsport</title>
    </sporttype>
    <sporttype id="4">
      <title>Hallensport</title>
    </sporttype>
</sporttypes>
